### ISSUE TITLE
Push rejected, no Cedar-supported app detected

### ISSUE THREAD

**Issue by steve21124** [ActiDoo/gamification-engine-dokku#2]
error in push => git push heroku master
]
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... done
remote: 
remote:  !     Push rejected, no Cedar-supported app detected
remote: HINT: This occurs when Heroku cannot detect the buildpack
remote:       to use for this application automatically.
remote: See https://devcenter.heroku.com/articles/buildpacks
remote: 
remote: Verifying deploy....
remote: 
remote: !   Push rejected to pure-earth-2878.
remote:

**Comment by msander** [comment]
Did you get it to work? I'm not sure how to set the correct buildpack in heroku, in dokku it's in the .env file. Nevertheless, it also works in our demo on heroku.
