### ISSUE TITLE
Heroku H10 error

### ISSUE THREAD

**Issue by romdim** [ActiDoo/gamification-engine-dokku#4]
Hello there.

I'm  trying for a lot of time now to push the g-engine to heroku but unfortunately I get an H10 error that the app has crashed. I haven't set up the sentry add-on as it costs a lot. So I don't have more logs than:

2016-01-26T17:38:02.080331+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cloudteams-gamification.herokuapp.com request_id=7ce63812-7ea6-4dd3-b8ac-6fa705b0114d fwd="212.251.48.128" dyno= connect= service= status=503 bytes=

How can I fix this? What is wrong? I have uploaded the latest version and run the initialization command.

Thanks in advance,
Romanos

**Comment by feldi-online** [comment]
Hi Romanos,

for helping you, I will need some more information. First of all I would be helpful, if you let me know when the exception excactly happens. Even better would be to include any logging addon. Instead of sentry you could add Papertrail (https://elements.heroku.com/addons/papertrail) for free to your Heroku app, which shows the console output.

Best,
Matthias

**Comment by romdim** [comment]
Hey @feldi88 , took me a while!
I installed papertrail and got same error as the one provided through the console using the heroku logs command:

Apr 05 03:21:40 cloud-gami heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/" host=cloud-gami.herokuapp.com request_id=f3d014f2-906b-4b17-afcc-97c56b5f293a fwd="147.102.6.98" dyno= connect= service= status=503 bytes= 

You can see different project name (cloud-gami) as I tried to start the process from scratch. Created a new heroku project, downloaded dokku zip. Extracted everything into folder, changed alembic and production inis to match my postgress credentials, pushed everything to heroku. It starts ok, I run the db initialization command exactly as is in the readme and when I try to access http://cloud-gami.herokuapp.com/ it throws an application error with the above message in the logs.

What am I doing wrong? Thank you very much in advance!

**Comment by feldi-online** [comment]
Hi Romanos,

sorry, but I cannot restore your error. I think it is a heroku problem.

Our instance is running without any problems at https://gamification-engine.herokuapp.com/ and I can also start new instances without any problems. I just checked our configuration at heroku and these are the parameters:

```
BUILDPACK_URL=https://github.com/ddollar/heroku-buildpack-multi.git
DATABASE_URL=postgres://*:*@*.eu-west-1.compute.amazonaws.com:5432/*
HEROKU_POSTGRESQL_SILVER_URL=postgres://*:*@*.eu-west-1.compute.amazonaws.com:5432/*
PAPERTRAIL_API_TOKEN=
URLCACHE_ACTIVE=False
```

(The \* are used here for security reasons.)

There are two dynos configured, but only the first one is turned on:

```
web sh bin/web.sh
mc memcached -l 127.0.0.1 -m 128
```

The last state from master (94f2093) is deployed.

You should double check the configuration, perhaps there is any error

**Comment by feldi-online** [comment]
Closing the issue since the deploy of the development (develop branch) and the stable version (master branch) runs without any problems. Please open the issue again if the problem appears again.
